# Generated by Django 2.1.4 on 2018-12-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubicacoesApp', '0005_auto_20181219_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='exclusoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Termo de procura',
                'verbose_name_plural': 'Termos de procura',
            },
        ),
    ]
