# Generated by Django 2.1.4 on 2018-12-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubicacoesApp', '0006_exclusoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exclusoes',
            old_name='campo',
            new_name='termo',
        ),
    ]
